#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "query.y".
#

require 'racc/parser.rb'

# generate using: racc query.y -o query.rb
# $debug = true
class Array
class QueryParser < Racc::Parser

module_eval(<<'...end query.y/module_eval...', 'query.y', 121)
  def parse(str)
    value_sub_subregex = '-\p{Hiragana}\p{Katakana}\p{Han}\p{Hangul}ー〜、a-zA-Z0-9_+*.⭐🩵💩'
    value_quoted_subregex = value_sub_subregex + "\|\(\) !?"
    value_subregex = "(\"[#{value_quoted_subregex}']+\"|'[#{value_quoted_subregex}\"]+'|[#{value_sub_subregex},]+)"
    @q = []
    until str.empty?
      case str
      when /\A\s+/ #ignore spaces
      when /\A(Like)\s+#{value_subregex}/
        @q.push [:SENSITIVE_LIKE, 'like']
        @q.push [:VALUE, $2.tr('"\'', '')]
      when /\A(all|in|has|like|textsearch)\s+#{value_subregex}/
        @q.push [$1, $1]
        @q.push [:VALUE, $2.tr('"\'', '')]
      when /\A#{value_subregex}(\s+)?/
        @q.push [:VALUE, $1.tr('"\'', '')]
        @q.push [:SPACE, ''] if $2
      when /\A[<>]=?/
        @q.push [:OP_NUM, $&]
      when /\A==|!=|\|\||&&|[!()\n]/o
        s = $&
        @q.push [s, s]
      else
        raise "could not tokenize '#{str}'"
      end
      str = $'
    end
    # puts "tokens: #{@q.inspect}" if $debug
    @q.push [false, '$end']
    do_parse
  end

  def next_token
    @q.shift
  end
...end query.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    11,    10,     3,    11,    10,     3,     9,     5,    12,    16,
     5,    20,    16,     6,     7,    33,     6,     7,     3,    16,
     3,    16,     3,     5,    32,     5,    11,     5,    16,     6,
     7,     6,     7,     6,     7,    23,    24,    25,    26,    27,
    28,    13,    14,    15,    16,    16,    16,    16,    16 ]

racc_action_check = [
    19,    19,     0,     2,     2,     6,     1,     0,     3,     5,
     6,     9,    13,     0,     0,    19,     6,     6,     7,    14,
    10,    15,    11,     7,    16,    10,    21,    11,    23,     7,
     7,    10,    10,    11,    11,    12,    12,    12,    12,    12,
    12,     4,     4,     4,    24,    25,    26,    27,    28 ]

racc_action_pointer = [
    -3,     6,     0,     2,    34,     4,     0,    13,   nil,    11,
    15,    17,    25,     7,    14,    16,    18,   nil,   nil,    -3,
   nil,    23,   nil,    23,    39,    40,    41,    42,    43,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -19,   -19,    -1,    -2,   -19,   -19,   -19,   -19,   -18,   -19,
   -19,   -19,    -3,   -19,   -19,   -19,    -2,    -7,   -16,   -19,
    40,   -14,   -15,   -19,   -19,   -19,   -19,   -19,   -19,    -4,
    -5,    -6,    -3,   -17,    -8,    -9,   -10,   -11,   -12,   -13 ]

racc_goto_table = [
    17,     1,   nil,   nil,   nil,     2,   nil,   nil,    29,    30,
    31,    18,    19,   nil,   nil,    21,    22,   nil,    34,    35,
    36,    37,    38,    39 ]

racc_goto_check = [
     3,     1,   nil,   nil,   nil,     2,   nil,   nil,     3,     3,
     3,     2,     2,   nil,   nil,     2,     2,   nil,     3,     3,
     3,     3,     3,     3 ]

racc_goto_pointer = [
   nil,     1,     5,    -5,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     4,     8 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 20, :_reduce_none,
  1, 22, :_reduce_none,
  2, 22, :_reduce_none,
  3, 23, :_reduce_4,
  3, 23, :_reduce_5,
  3, 23, :_reduce_6,
  2, 23, :_reduce_7,
  4, 23, :_reduce_8,
  4, 23, :_reduce_9,
  4, 23, :_reduce_10,
  4, 23, :_reduce_11,
  4, 23, :_reduce_12,
  4, 23, :_reduce_13,
  3, 21, :_reduce_14,
  3, 21, :_reduce_15,
  2, 21, :_reduce_16,
  3, 21, :_reduce_17,
  1, 21, :_reduce_none ]

racc_reduce_n = 19

racc_shift_n = 40

racc_token_table = {
  false => 0,
  :error => 1,
  :UNEG => 2,
  "&&" => 3,
  "||" => 4,
  :VALUE => 5,
  :SPACE => 6,
  "==" => 7,
  "!=" => 8,
  :OP_NUM => 9,
  "has" => 10,
  "in" => 11,
  "all" => 12,
  "textsearch" => 13,
  "like" => 14,
  :SENSITIVE_LIKE => 15,
  "!" => 16,
  "(" => 17,
  ")" => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "UNEG",
  "\"&&\"",
  "\"||\"",
  "VALUE",
  "SPACE",
  "\"==\"",
  "\"!=\"",
  "OP_NUM",
  "\"has\"",
  "\"in\"",
  "\"all\"",
  "\"textsearch\"",
  "\"like\"",
  "SENSITIVE_LIKE",
  "\"!\"",
  "\"(\"",
  "\")\"",
  "$start",
  "target",
  "exp",
  "val",
  "query" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'query.y', 13)
  def _reduce_4(val, _values, result)
          # puts "eql #{val}" if $debug
      result = lambda{|h| h[val[0]].to_s == val[2]}

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 17)
  def _reduce_5(val, _values, result)
          # puts "not #{val}" if $debug
      result = lambda{|h| h[val[0]].to_s != val[2]}

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 21)
  def _reduce_6(val, _values, result)
          # puts "num #{val}" if $debug
      result = lambda{|h| h[val[0]].to_f.send(val[1].to_sym, val[2].to_f) }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 25)
  def _reduce_7(val, _values, result)
          # puts "has #{val}" if $debug
      result = lambda{|h| !(!h.has_key?(val[1]) || h[val[1]].nil? || h[val[1]] == '' ) }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 29)
  def _reduce_8(val, _values, result)
          # puts "has #{val}" if $debug
      raise 'this syntax is deprecated use "field like regex"'

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 33)
  def _reduce_9(val, _values, result)
          # puts "in #{val}" if $debug
      vals = val[3].split(',').map(&:strip)
      result = lambda{|h|
        if not h.has_key?(val[0])
          raise "key '#{val[0]}' not found"
        elsif h[val[0]].class == Array
          (h[val[0]] & vals).any?
        else
          vals.include?(h[val[0]].to_s)
        end
      }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 46)
  def _reduce_10(val, _values, result)
          # puts "all #{val}" if $debug
      vals = val[3].split(',').map(&:strip)
      result = lambda{|h|
        if not h.has_key?(val[0])
          raise "key '#{val[0]}' not found"
        elsif h[val[0]].class == Array
          (vals - h[val[0]]).empty?
        else
          false
        end
      }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 59)
  def _reduce_11(val, _values, result)
          # puts "textsearch #{val}" if $debug
      regexp = /#{val[3]}/i
      result = lambda{|h|
        cleanup = lambda{|v| v.gsub(/[.,:;!?'"-]/,' ').gsub(/\s\s+/, ' ')}
        if not h.has_key?(val[0])
          raise "key '#{val[0]}' not found"
        elsif h[val[0]].class == Array
          h[val[0]].any?{|v| cleanup[v].match?(regexp)}
        else
          cleanup[h[val[0]]].match?(regexp)
        end
      }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 73)
  def _reduce_12(val, _values, result)
          # puts "like #{val}" if $debug
      regexp = /#{val[3]}/i
      result = lambda{|h|
        if not h.has_key?(val[0])
          raise "key '#{val[0]}' not found"
        elsif h[val[0]].class == Array
          h[val[0]].any?{|v| v.match?(regexp)}
        else
          h[val[0]].match?(regexp)
        end
      }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 86)
  def _reduce_13(val, _values, result)
          # puts "sensitive like #{val}" if $debug
      regexp = /#{val[3]}/
      result = lambda{|h|
        if not h.has_key?(val[0])
          raise "key '#{val[0]}' not found"
        elsif h[val[0]].class == Array
          h[val[0]].any?{|v| v.match?(regexp)}
        else
          h[val[0]].match?(regexp)
        end
      }

    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 101)
  def _reduce_14(val, _values, result)
          # puts 'or' if $debug
      result = lambda{|h| val[0][h] || val[2][h]}
    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 104)
  def _reduce_15(val, _values, result)
          # puts 'and' if $debug
      result = lambda{|h| val[0][h] && val[2][h]}
    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 107)
  def _reduce_16(val, _values, result)
          # puts 'not' if $debug
      result = lambda{|h| ! val[1][h] }
    result
  end
.,.,

module_eval(<<'.,.,', 'query.y', 110)
  def _reduce_17(val, _values, result)
          # puts 'brack' if $debug
      result = val[1]
    result
  end
.,.,

# reduce 18 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class QueryParser

  def query(str)
    # puts "parsin" if $debug
    # puts str if $debug
    fun = QueryParser.new.parse(str)
    return self.select{|h|fun[h]}
  end
end
x = [
  {'a' => '1', 'b' => '1', 'c' => '3', 'd' => ['a', 'b', 'HIあああo']},
  {'a' => '1', 'b' => '2', 'c' => '3.4', 'd' => ['a', 'c']},
  {'a' => '1', 'b' => '2', 'c' => '4', 'd' => ['a', 'アあ']},
  {'a' => '1', 'b' => '2', 'c' => '4', 'd' => 'asd'},
  {'e' => '1', 'c' => '', 'd' => ''},
]
raise 'ah' unless x.query('!a == 1') == x.select{|h| h['a'] != '1'}
raise 'ahh' unless x.query('(!(!(a==1))&& b == 2)') == x.select{|h| h['a'] == '1' && h['b'] == '2'}
raise 'ahhh' unless x.query('c == 1 && b != 2') == x.select{|h| h['c'] == '1' && h['b'] != '2'}
raise 'ahhh2' unless x.query('c == 1 || b == 2') == x.select{|h| h['c'] == '1' || h['b'] == '2'}
raise 'ahhhh' unless x.query('c == 1 || b == 2 && c != 4') == x.select{|h| h['c'] == '1' || h['b'] == '2' && h['c'] != '4'}
raise 'ahhhhh' unless x.query('c == 1 || b == 2 && c != 4') == x.select{|h| h['c'] == '1' || (h['b'] == '2' && h['c'] != '4')}
raise 'ahhhhhh' unless x.query('(c == 1 || b == 2) && c != 4') == x.select{|h| (h['c'] == '1' || h['b'] == '2') && h['c'] != '4'}
raise 'ahhhhhhh' unless x.query('b != 2 || (c == 1 || b == 2) && c != 4') == x.select{|h| h['b'] != '2' || (h['c'] == '1' || h['b'] == '2') && h['c'] != '4'}
# raise 'ahhhhhhhh' unless x.query('d has d') == x.select{|h| [Array, String].include?(h['d'].class) && h['d'].include?('d')}
# raise 'ahhhhhhhhh' unless x.query('!(d has b)') == x.select{|h| ! h['d'].include?('b')}
# raise 'ahhhhhhhhhh' unless x.query('d has asd') == x.select{|h| h['d'].class == String && h['d'] == 'asd'}
raise 'ahhhhhhhhhhh' unless x.query('c > 3') == x.select{|h| h['c'].to_f > 3}
raise 'ahhhhhhhhhhhh' unless x.query('c > 3.3') == x.select{|h| h['c'].to_f > 3.3}
raise 'ahhhhhhhhhhhhh' unless x.query('(c > 2) || (c < 9)') == x.select{|h| h['c'].to_f > 2 || h['c'].to_f < 9}
raise 'ahhhhhhhhhhhhhh' unless x.query('c in 3,4') == x.select{|h| %w(3 4).include?(h['c'])}
raise 'ahhhhhhhhhhhhhhh' unless x.query('d in a,4') == x.select{|h| (%w(a 4) & h['d']).any? rescue false}
raise 'ahhhhhhhhhhhhhhhh' unless x.query('d all a,c') == x.select{|h| (%w(a c) - h['d']).empty? rescue false}
raise 'ahhhhhhhhhhhhhhhhh' unless x.query('d like あ+') == x.select{|h| h['d'].any?{|v| v.match?(/あ+/)} rescue false}
raise 'ahhhhhhhhhhhhhhhhha' unless x.query('d like hi') == x.select{|h| h['d'].any?{|v| v.match?(/^hi/i)} rescue false}
raise 'ahhhhhhhhhhhhhhhhhb' unless x.query('d like HI') == x.select{|h| h['d'].any?{|v| v.match?(/^HI/i)} rescue false}
raise 'ahhhhhhhhhhhhhhhhhc' unless x.query('d Like HI') == x.select{|h| h['d'].any?{|v| v.match?(/^HI/)} rescue false}
raise 'ahhhhhhhhhhhhhhhhhd' unless x.query('d Like hi') == x.select{|h| h['d'].any?{|v| v.match?(/^hi/)} rescue false}
raise 'ahhhhhhhhhhhhhhhhhh' unless x.query('d Like "hi"') == x.select{|h| h['d'].any?{|v| v.match?(/^hi/)} rescue false}
raise 'ahhhhhhhhhhhhhhhhhhh' unless x.query('has e') == x.select{|h| h.has_key?('e')}
raise 'ahhhhhhhhhhhhhhhhhhhh' unless x.query('has d') == x.select{|h| !(h['d'].nil? || h['d'] == '')}
[
  'c++',
  '(c) > 3',
  'c !> 3',
  '(c > 3',
  'c > 3)',
  'ahasb = b',
  'a == "b,',
  'a == \'b,',
  'a == b == c',
  'a has b has c',
  'a in b in c',
  'a all b all c',
  'a > b > c',
  'a like (a)',
  'a like ""',
  'a like \'\'',
  'a like \'a"',
  'a like "a\'',
  'a like [a]',
  'd has d',
  '!(d has b)',
  'd has asd',
].each_with_index do |str, i|
  begin
    x.query(str)
    raise ('ahn'+ 'o'*i) + ': ' + str
  rescue Racc::ParseError => e
    raise ('ahhn'+ 'o'*i) + ': ' + str unless e.to_s.strip.start_with?("parse error on value")
  rescue RuntimeError => e
    raise ('ahhn'+ 'o'*i) + ': ' + str unless e.to_s.start_with?('could not tokenize ') || e.to_s.start_with?('this syntax is deprecated use "field like regex"')
  end
end
# $debug = false
